name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./seat/pom.xml
          mvn clean package -f ./hr/pom.xml
          mvn clean package -f ./reserve/pom.xml
          mvn clean package -f ./dashboard/pom.xml

      - name: Docker Build and push for Seat
        uses: docker/build-push-action@v4
        with:
          context: ./seat
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/seat:latest
            ghcr.io/${{ github.repository }}/seat:${{ github.ref_name }}
            
      - name: Docker Build and push for Hr
        uses: docker/build-push-action@v4
        with:
          context: ./hr
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/hr:latest
            ghcr.io/${{ github.repository }}/hr:${{ github.ref_name }}
            
      - name: Docker Build and push for Reserve
        uses: docker/build-push-action@v4
        with:
          context: ./reserve
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/reserve:latest
            ghcr.io/${{ github.repository }}/reserve:${{ github.ref_name }}
            
      - name: Docker Build and push for Dashboard
        uses: docker/build-push-action@v4
        with:
          context: ./dashboard
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/dashboard:latest
            ghcr.io/${{ github.repository }}/dashboard:${{ github.ref_name }}
            
