server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: seat
          uri: http://localhost:8082
          predicates:
            - Path=/undefined/**, 
        - id: hr
          uri: http://localhost:0
          predicates:
            - Path=/hrs/**, 
        - id: reserve
          uri: http://localhost:0
          predicates:
            - Path=/undefined/**, 
        - id: dashboard
          uri: http://localhost:0
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: seat
          uri: http://seat:8080
          predicates:
            - Path=/undefined/**, 
        - id: hr
          uri: http://hr:8080
          predicates:
            - Path=/hrs/**, 
        - id: reserve
          uri: http://reserve:8080
          predicates:
            - Path=/undefined/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
